version: "3.8"

services:
  game-server:
    build:
      context: .
      dockerfile: apps/game-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    expose:
      - 80
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        - VITE_WS_URL=ws://game-server:8080
