version: "3.8"

services:
  game-server:
    build:
      context: .
      dockerfile: apps/game-server/Dockerfile
    expose:
      - 8080
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    expose:
      - 80
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        - VITE_WS_URL=${GAME_SERVER_URL:-ws://localhost:8080}

networks:
  dokploy-network:
    external: true
